model:
  channels: 32
  num_blocks: 7
  semantic_classes: 23
  instance_classes: 22
  sem2ins_classes: []
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
#    class_numpoint_mean: [-1., -1., 3917., 12056., 2303.,
#                          8331., 3948., 3166., 5629., 11719.,
#                          1003., 3317., 4912., 10221., 3889.,
#                          4136., 2120., 945., 3967., 2589.]
    class_numpoint_mean: [ 3186., 4039., 992., 2706., 99., 732., 69., 2922., 1531., 1111.,
                            1331., 77., 272., 174., 390., 726., 776., 2740., 523., 1262., 1522., 2852., -1]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0, 1]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    eval_tasks: ['semantic']
  fixed_modules: []

data:
  train:
    type: 'scannetv2'
    data_root: '/data1/szh/softgroup'
    prefix: 'train'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetv2'
    data_root: '/data1/szh/softgroup'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    with_label: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
dataloader:
  train:
    batch_size: 4
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.004

fp16: False
epochs: 128
step_epoch: 50
save_freq: 4
pretrain: '/data1/szh/softgroup/hais_ckpt_spconv2.pth'
work_dir: '/data1/szh/softgroup/work_backbone_dir'
